apiVersion: batch/v1
kind: Job
metadata:
  name: rhub-restore-{{ .Values.restoreId }}
spec:
  template:
    spec:
      containers:
      - name: rhub-restore-{{ .Values.restoreId }}
        image: restorehub/k8sconnector:v0.3
        imagePullPolicy: IfNotPresent
        command: ["./connector",  "-snapshot", "{{ .Values.restoreId }}"]
      restartPolicy: Never
  backoffLimit: 50

# spec:
#  repoName: {{ .Values.repoName }}
#  snapshotId: {{ .Values.snapshotId }}
#  restoreId: {{ .Values.restoreId }}
