apiVersion: batch/v1
kind: Job
metadata:
  name: rhub-restore-{{ .Values.restoreId }}
spec:
  template:
    spec:
      containers:
      - name: rhub-restore-{{ .Values.restoreId }}
        image: curlimages/curl:7.76.1
        imagePullPolicy: Always
        command:  ["curl",  "gmbadges-restorehub.gm.svc.cluster.local:30900/restores", "--data", '{"SnapshotId":"{{ .Values.snapshotId }}", "RepoName": "{{ .Values.repoName }}", "SnapshotName": "{{ .Values.snapshotName }}", "ID": "{{ .Values.restoreId }}" }']
      restartPolicy: Never
  backoffLimit: 50

